# Generated by Django 4.1 on 2022-09-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='book_title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
    ]
