# Generated by Django 4.1 on 2022-09-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0002_rename_name_author_author_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='desc',
        ),
    ]
